<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 7 - Midterm Review</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="custom.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Andrew Wang</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">About</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    CS&amp;SS 321
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="teaching.html">Overview</a>
    </li>
    <li>
      <a href="lab1.html">Week 1</a>
    </li>
    <li>
      <a href="lab2.html">Week 2</a>
    </li>
    <li>
      <a href="lab3.html">Week 3</a>
    </li>
    <li>
      <a href="lab4.html">Week 4</a>
    </li>
    <li>
      <a href="lab5.html">Week 5</a>
    </li>
    <li>
      <a href="lab6.html">Week 6</a>
    </li>
    <li>
      <a href="lab7.html">Week 7</a>
    </li>
    <li>
      <a href="lab8.html">Week 8</a>
    </li>
    <li>
      <a href="lab9.html">Week 9</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Research
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="research.html">Papers</a>
    </li>
    <li>
      <a href="CV.html">CV</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Toys
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="simmodel.html">Protest-Repression Model</a>
    </li>
    <li>
      <a href="pdlparking.html">Should I Pay to Park in PDL?</a>
    </li>
    <li>
      <a href="regplot.html">Visualizing Multiple Regression</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lab 7 - Midterm Review</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#instructions" id="toc-instructions"><span
class="toc-section-number">1</span> Instructions</a></li>
<li><a href="#part-i-causal-inference"
id="toc-part-i-causal-inference"><span
class="toc-section-number">2</span> Part I — Causal Inference</a></li>
<li><a href="#part-ii-prediction" id="toc-part-ii-prediction"><span
class="toc-section-number">3</span> Part II — Prediction</a></li>
</ul>
</div>

<div id="instructions" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Instructions</h1>
<p>There are two parts: Part I (Causal Inference), Part II (Prediction).
Use clear causal language and avoid causal claims for purely predictive
models. Show work for any calculations.The data and required libraries
are loaded with the chunk below.</p>
<pre class="r"><code>data(Seatbelts, package = &quot;datasets&quot;)
data(swiss, package = &quot;datasets&quot;)
sb_df &lt;- cbind.data.frame(as.data.frame(Seatbelts))
sb_df$year &lt;- rep(1969:1984, each = 12)
sb_df$month &lt;- rep(1:12, times = 16)

sw &lt;- swiss</code></pre>
</div>
<div id="part-i-causal-inference" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Part I — Causal
Inference</h1>
<p>Research Question: Did the introduction of the 1983 seat belt law in
the UK reduce the number of monthly driver fatalities?</p>
<blockquote>
<p>Dataset: Seatbelts</p>
<ul>
<li><code>DriversKilled</code> (monthly count)</li>
<li><code>law</code> (0 = before Jan 1983, 1 = after)</li>
<li><code>month</code></li>
<li><code>kms</code> (traffic volume)</li>
<li><code>PetrolPrice</code></li>
<li><code>VanKilled</code></li>
</ul>
</blockquote>
<ol style="list-style-type: decimal">
<li>Research Design &amp; Concepts</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>What should we set as the outcome variable? What about the treatment
variable?</li>
</ol>
<blockquote>
<p>The outcome variable is <code>DriversKilled</code>. The treatment
variable is <code>law</code>.</p>
</blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>What is the unit of analysis?</li>
</ol>
<blockquote>
<p>The unit of analysis is the number of drivers killed per month.</p>
</blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Why is this considered an observational rather than experimental
study?</li>
</ol>
<blockquote>
<p>This study is observational since the researchers do not determine
the treatment assignment.</p>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Average Causal Effect — Difference in Means Write R code to estimate
the difference in average DriversKilled before and after the law change.
You may use any method you know but <code>tapply()</code> is
recommended.</li>
</ol>
<blockquote>
<p>Example R code using <code>tapply()</code> and without:</p>
</blockquote>
<pre class="r"><code>means &lt;- tapply(sb_df$DriversKilled, sb_df$law, mean)
means[1]-means[2]</code></pre>
<pre><code>##        0 
## 25.60895</code></pre>
<pre class="r"><code>(mean(sb_df$DriversKilled[sb_df$law == 1]) - mean(sb_df$DriversKilled[sb_df$law == 0]))</code></pre>
<pre><code>## [1] -25.60895</code></pre>
<ol style="list-style-type: lower-alpha">
<li>What quantity does this code estimate?</li>
</ol>
<blockquote>
<p>This code estimates the effect of the passage of the seatbelt law on
the number of drivers killed.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>In 2–3 sentences, explain why this estimate might be biased.</li>
</ol>
<blockquote>
<p>The estimate may be biased because variables are omitted from the
calculation of the effect. In the case of a binary predictor, difference
in means estimator is equivalent to the coefficient on the binary
predictor in a simple linear regression model (see below). Without
controlling for confounding variables, the effect of these confounders
would be incorporated into the model via the residuals (<span
class="math inline">\(\varepsilon_i\)</span>), meaning <span
class="math inline">\(\mathbb{E}[\varepsilon_i] \neq 0\)</span>, which
means that the effect <span class="math inline">\(\beta_1\)</span> would
be biased.</p>
</blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Simple Linear Regression Interpretation Suppose you estimate:</li>
</ol>
<pre class="r"><code>m1 &lt;- lm(DriversKilled ~ law, data = sb_df)
summary(m1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = DriversKilled ~ law, data = sb_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -46.870 -17.870  -5.565  14.130  72.130 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  125.870      1.849  68.082  &lt; 2e-16 ***
## law          -25.609      5.342  -4.794 3.29e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 24.03 on 190 degrees of freedom
## Multiple R-squared:  0.1079, Adjusted R-squared:  0.1032 
## F-statistic: 22.98 on 1 and 190 DF,  p-value: 3.288e-06</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Write the fitted regression equation.</li>
</ol>
<blockquote>
<p>The regression equation is:</p>
</blockquote>
<p><span class="math display">\[
\texttt{DriversKilled}_i = \beta_0 + \beta_1\texttt{law}_i +
\varepsilon_i
\]</span></p>
<blockquote>
<p>The fitted regression equation is:</p>
</blockquote>
<p><span class="math display">\[
\texttt{DriversKilled}_i = 126 - 25.6\texttt{law}_i + \varepsilon_i
\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Interpret the coefficients clearly in terms of this study. &gt;
<span class="math inline">\(\beta_0\)</span> is the contant term. The
value of the constant indicates to us the expected number of drivers
killed when <code>law</code><span class="math inline">\(=0\)</span>. In
other words, the number of drivers killed when there is no seatbelt
law.</li>
</ol>
<blockquote>
<p><span class="math inline">\(\beta_1\)</span> is the effect of
<code>law</code>. That is, when <code>law</code> increases by <span
class="math inline">\(1\)</span>, the number of drivers killed should
increase by <span class="math inline">\(\beta_1\)</span>. In this case,
with a binary predictor <code>law</code>, this means the effect of
having a seatbelt law is that <span
class="math inline">\(\beta_1\)</span> more drivers are killed (note
that <span class="math inline">\(\beta_1\)</span> is likely negative,
and therefore the effect should be a decrease in the number of drivers
killed). c) Can this coefficient be interpreted as a causal effect? Why
or why not? Which variable(s) might be a confounder?</p>
</blockquote>
<blockquote>
<p>The coefficient <span class="math inline">\(\beta_1\)</span> cannot
be interpreted as a causal effect because this effect may be confounded
by other variables. For instance, there may have been more cars on the
road after the passage of the law than before, which would indicate that
<span class="math inline">\(\beta_1\)</span> could be an underestimate
of the effect of the seatbelt law.</p>
</blockquote>
<ol start="4" style="list-style-type: decimal">
<li>Confounding &amp; Observational Design Name one specific variable
that could confound the relationship between law and DriversKilled.
Explain why it is a confounder.</li>
</ol>
<blockquote>
<p>See Above</p>
</blockquote>
<ol start="5" style="list-style-type: decimal">
<li>External Validity Would you expect this result to generalize to
other countries? Would it generalize to the modern-day? Explain why or
why not using correct causal language.</li>
</ol>
<blockquote>
<p>Other determinants of <code>DriversKilled</code> may have changed
significantly from the period of observation of this study to now. For
instance, the rate of drunk driving may have fallen dramatically. If
more drunk driving causes less seatbelt usage and more drivers killed,
then estimating the causal effect of the seatbelt law would require
including drunk driving rates as a confounding variable.</p>
</blockquote>
</div>
<div id="part-ii-prediction" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Part II —
Prediction</h1>
<p>Research Question: Can socio-economic indicators predict fertility
rates in Swiss provinces?</p>
<blockquote>
<p>Dataset: <code>swiss</code></p>
<ul>
<li><code>province</code></li>
<li><code>Fertility</code></li>
<li><code>Education</code></li>
<li><code>Catholic</code></li>
<li><code>Agriculture</code></li>
<li><code>Infant.Mortality</code></li>
</ul>
</blockquote>
<ol start="6" style="list-style-type: decimal">
<li>Direction &amp; Strength of Relationship Consider this scatter plot
of Fertility vs Education.</li>
</ol>
<pre class="r"><code>plot(Fertility ~ Education, data = sw,
xlab = &quot;Education (%) beyond primary (men)&quot;,
ylab = &quot;Standardized Fertility&quot;); abline(lm(Fertility ~ Education, data = sw))</code></pre>
<p><img src="lab7_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<ol style="list-style-type: lower-alpha">
<li>Draw a line of best fit by hand. Is the relationship positive or
negative?</li>
</ol>
<blockquote>
<p>Line of best fit shown in plot. The relationship is negative.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Does it look strong or weak?</li>
</ol>
<blockquote>
<p>There seems to be a significant (good line fit) relationship, and the
magnitude of the relationship looks strong (steep slope).</p>
</blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Does this plot alone tell us if education causes lower fertility?
Explain.</li>
</ol>
<blockquote>
<p>This plot alone does not tell us if education causes lower fertility
as there are potential confounding variables not controlled for in the
model. For instance, higher poverty in a region may cause higher
fertility and lower education.</p>
</blockquote>
<ol start="7" style="list-style-type: decimal">
<li>Simple Regression with lm() Using <code>lm()</code>, write a script
to model the effect of education quality on fertility.</li>
</ol>
<blockquote>
<p>The code is shown below</p>
</blockquote>
<pre class="r"><code>g1 &lt;- lm(Fertility ~ Education, data = sw)
summary(g1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ Education, data = sw)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.036  -6.711  -1.011   9.526  19.689 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  79.6101     2.1041  37.836  &lt; 2e-16 ***
## Education    -0.8624     0.1448  -5.954 3.66e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.446 on 45 degrees of freedom
## Multiple R-squared:  0.4406, Adjusted R-squared:  0.4282 
## F-statistic: 35.45 on 1 and 45 DF,  p-value: 3.659e-07</code></pre>
<p>Assume the output shows: <span class="math inline">\(\hat{\alpha} =
79.6\)</span>, <span class="math inline">\(\hat{\beta} =
-0.86\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>Write the fitted line.</li>
</ol>
<blockquote>
<p>The fitted line is:</p>
</blockquote>
<p><span class="math display">\[
\texttt{Fertility}_i = 79.6 - 0.86 \texttt{Education}_i + \varepsilon_i
\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Interpret <span class="math inline">\(\hat{\beta}\)</span>: If
<code>Education</code> increases by 1 unit (1 percentage point of men
with post-primary education), how does predicted <code>fertility</code>
change?</li>
</ol>
<blockquote>
<p>Each 1 unit increase in <code>Education</code> corresponds to a 0.86
unit decrease in <code>fertility</code>.</p>
</blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Predict <code>fertility</code> when <code>Education</code> =
15.</li>
</ol>
<blockquote>
<p>We can simply plug in <code>Education</code> = 15 into the model
above. In this case <code>Fertility</code> <span
class="math inline">\(79.6 - 0.86 \times 15 = 66.7\)</span>.</p>
</blockquote>
<ol start="8" style="list-style-type: decimal">
<li>Multiple Regression: Adding Control Variables Now predict
<code>fertility</code> using <code>Education</code>,
<code>Catholic</code>, and <code>Infant.Mortality</code>. Write a script
to evaluate the model, then write out the fitted equation using:</li>
</ol>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ Education + Catholic + Infant.Mortality, 
##     data = sw)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.4781  -5.4403  -0.5143   4.1568  15.1187 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      48.67707    7.91908   6.147 2.24e-07 ***
## Education        -0.75925    0.11680  -6.501 6.83e-08 ***
## Catholic          0.09607    0.02722   3.530  0.00101 ** 
## Infant.Mortality  1.29615    0.38699   3.349  0.00169 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.505 on 43 degrees of freedom
## Multiple R-squared:  0.6625, Adjusted R-squared:  0.639 
## F-statistic: 28.14 on 3 and 43 DF,  p-value: 3.15e-10</code></pre>
<blockquote>
<p>The model can be evaluated with</p>
</blockquote>
<pre class="r"><code>g2 &lt;- lm(Fertility ~ Education + Catholic + Infant.Mortality, data = sw)
summary(g2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ Education + Catholic + Infant.Mortality, 
##     data = sw)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.4781  -5.4403  -0.5143   4.1568  15.1187 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      48.67707    7.91908   6.147 2.24e-07 ***
## Education        -0.75925    0.11680  -6.501 6.83e-08 ***
## Catholic          0.09607    0.02722   3.530  0.00101 ** 
## Infant.Mortality  1.29615    0.38699   3.349  0.00169 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.505 on 43 degrees of freedom
## Multiple R-squared:  0.6625, Adjusted R-squared:  0.639 
## F-statistic: 28.14 on 3 and 43 DF,  p-value: 3.15e-10</code></pre>
<blockquote>
<p>The fitted equation is</p>
</blockquote>
<p><span class="math display">\[
\texttt{Fertility}_i = 48.7 - 0.759 \texttt{Education}_i +
0.0961\texttt{Catholic}_i + 1.30\texttt{Infant.Mortality}_i +
\varepsilon_i
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Why might we add more predictors in a prediction-focused model? Why
might we not want to add too many?</li>
</ol>
<blockquote>
<p>Adding more predictors always improves model fit. Thus the model with
more predictors will be better at predicting outcomes within our sample.
However, adding more predictors risks over-fitting the model. This means
that a model with too many predictors may be worse at predicting
outcomes outside of our sample.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>If the magnitude of <span class="math inline">\(\hat{\beta}\)</span>
for Education changes after adding variables, what does that suggest (in
terms of confounding or omitted variable bias)?</li>
</ol>
<blockquote>
<p>This would suggest that the effect of education was partially
explained by the newly added variables. This means that the newly added
variables were likely confounders of the effect of education. Regardless
of the change in magnitude of <span
class="math inline">\(\hat{\beta}\)</span>, any significantly non-zero
coefficient on the newly added variables indicates that the former model
had omitted variable bias.</p>
</blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Why is this not a causal study?</li>
</ol>
<blockquote>
<p>This is not a causal study because there is no theoretical
justification for including the new predictors. Their inclusion is
solely intended to improve model fit, not to remove the effect of
confounders that we have justified through theory. If this model were
justified theoretically first, this could be a causal study.</p>
</blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Explain the difference between predicting fertility and estimating
causal effects of education on fertility. Why would it be inappropriate
to say “increasing education will cause fertility to fall” based only on
this regression?</li>
</ol>
<blockquote>
<p>Again, without adequate justification that this model includes all
potential confounders and only potential confounders, this regression
cannot help us make causal claims about the effect of education.</p>
</blockquote>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
